timezone: Europe/Berlin
notion:
  database_id: 28c974ad-ea9a-81a6-99f7-f905e67ee507
  parent_page_id: 36b971c0016a4b11849c56016a2c8be9
  aggregate_daily: false
time:
  daily_window_local:
    from: yesterday 00:00:00
    to: today 23:59:59
  include_merges: false
  diff_base: first-parent
classify:
  frontend_globs:
  - '**/*.js'
  - '**/*.jsx'
  - '**/*.ts'
  - '**/*.tsx'
  - '**/*.vue'
  - '**/*.css'
  - '**/*.scss'
  - '**/*.less'
  - '**/*.html'
  - '**/*.svelte'
  - frontend/**
  - web/**
  backend_globs:
  - '**/*.py'
  - '**/*.java'
  - '**/*.go'
  - '**/*.rs'
  - '**/*.rb'
  - '**/*.php'
  - '**/*.cs'
  - '**/*.kt'
  - '**/*.scala'
  - '**/*.sh'
  - '**/*.sql'
  - backend/**
  - server/**
repos:
- platform: github
  owner: yiliang.guo
  repo: allen_ai_tools
  branch: main
  local_cache_dir: /Users/mac/Develop/yiliang/allen_ai_tools
  since_days: 7
- platform: gitee
  owner: yiliang.guo
  repo: cxp9-fe
  branch: master
  local_cache_dir: /Users/mac/Develop/Gitee/cxp9-fe
  since_days: 7
