name: Daily Commit Sync

on:
  schedule:
    # 06:05 UTC ~= 08:05 Europe/Berlin (adjust for DST as needed)
    - cron: "5 6 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure git
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "git-notion-sync-bot"
      - name: Run sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          python main.py
      - name: Persist state
        if: always()
        run: |
          echo "::group::Show state.json"
          [ -f state.json ] && cat state.json || echo "no state"
          echo "::endgroup::"
